// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8zskJnaJG-BghhvEBXdJjta72eYbtFFc',
    appId: '1:469713840000:web:771159244e4257c692c365',
    messagingSenderId: '469713840000',
    projectId: 'codejam-bd821',
    authDomain: 'codejam-bd821.firebaseapp.com',
    storageBucket: 'codejam-bd821.appspot.com',
    measurementId: 'G-0JD51SFWW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZiFS32ByxLQsILwRq315qZ5gqBRDQdVQ',
    appId: '1:469713840000:android:3827ddf307c5e0de92c365',
    messagingSenderId: '469713840000',
    projectId: 'codejam-bd821',
    storageBucket: 'codejam-bd821.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9JS61qDbJ7nJf2Jlb36q3x0yM8wRqP4s',
    appId: '1:469713840000:ios:dae1bb1dab4d12de92c365',
    messagingSenderId: '469713840000',
    projectId: 'codejam-bd821',
    storageBucket: 'codejam-bd821.appspot.com',
    iosBundleId: 'com.example.codejam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9JS61qDbJ7nJf2Jlb36q3x0yM8wRqP4s',
    appId: '1:469713840000:ios:f6dcba1a490d11c292c365',
    messagingSenderId: '469713840000',
    projectId: 'codejam-bd821',
    storageBucket: 'codejam-bd821.appspot.com',
    iosBundleId: 'com.example.codejam.RunnerTests',
  );
}
